<a href="https://colab.research.google.com/github/Mahadasim/Data_Practice/blob/master/DS_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [33]:
data = pd.read_csv("/content/weatherAUS.csv")
print(data.head)

<bound method NDFrame.head of               Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  \
0       2008-12-01   Albury     13.4     22.9       0.6          NaN   
1       2008-12-02   Albury      7.4     25.1       0.0          NaN   
2       2008-12-03   Albury     12.9     25.7       0.0          NaN   
3       2008-12-04   Albury      9.2     28.0       0.0          NaN   
4       2008-12-05   Albury     17.5     32.3       1.0          NaN   
...            ...      ...      ...      ...       ...          ...   
145455  2017-06-21    Uluru      2.8     23.4       0.0          NaN   
145456  2017-06-22    Uluru      3.6     25.3       0.0          NaN   
145457  2017-06-23    Uluru      5.4     26.9       0.0          NaN   
145458  2017-06-24    Uluru      7.8     27.0       0.0          NaN   
145459  2017-06-25    Uluru     14.9      NaN       0.0          NaN   

        Sunshine WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  \
0            NaN           W  

In [23]:
X = data.drop(["Date","Evaporation","Sunshine", "RainTomorrow"],axis=1)
X = X.values
Y = data['RainTomorrow'].values

In [24]:
Y = Y.reshape(-1,1)
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 [nan]]


In [132]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy="most_frequent")
X = imputer.fit_transform(X)

In [133]:
print(X)

[[ 2.00000000e+00  1.91327532e-01 -4.13597721e-02 ... -1.40707746e-02
   2.31036247e-02  0.00000000e+00]
 [ 2.00000000e+00 -7.51052308e-01  2.68744522e-01 ...  3.24466319e-02
   3.87798995e-01  0.00000000e+00]
 [ 2.00000000e+00  1.12795879e-01  3.53318420e-01 ...  6.21667115e-01
   2.27333032e-01  0.00000000e+00]
 ...
 [ 4.10000000e+01 -1.06517892e+00  5.22466217e-01 ... -6.96326071e-01
   6.50379662e-01  0.00000000e+00]
 [ 4.10000000e+01 -6.88226986e-01  5.36561867e-01 ... -2.93175214e-01
   6.35791847e-01  0.00000000e+00]
 [ 4.10000000e+01  4.26922492e-01 -4.50133614e-01 ... -3.08681016e-01
  -1.08186709e-01  0.00000000e+00]]


In [134]:
print(Y)

[0 0 0 ... 0 0 0]


In [136]:
Y = Y.reshape(-1,1)

In [137]:
from sklearn.preprocessing import LabelEncoder

In [138]:
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,4] = le2.fit_transform(X[:,4])
le3 = LabelEncoder()
X[:,6] = le3.fit_transform(X[:,6])
le4 = LabelEncoder()
X[:,7] = le4.fit_transform(X[:,7])
le5 = LabelEncoder()
X[:,-1] = le5.fit_transform(X[:,-1])
le6 = LabelEncoder()
Y[:,-1] = le6.fit_transform(Y[:,-1])

In [139]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [140]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.2, random_state=0)

In [148]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators=100,random_state=0)
classifier.fit(X_train,Y_train)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestClassifier(random_state=0)

In [149]:
classifier.score(X_train,Y_train)

0.9999312525780283

In [151]:
y_pred = le6.inverse_transform(np.array(classifier.predict(X_test),dtype=int))
Y_test = le6.inverse_transform(np.array(Y_test,dtype=int))

In [152]:
print(y_pred)

[0 0 0 ... 0 0 0]


In [154]:
print(Y_test)

[1 1 0 ... 1 0 0]


In [155]:
y_pred = y_pred.reshape(-1,1)
Y_test = Y_test.reshape(-1,1)

In [157]:
df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Rain on Tommorrow','Predition of Rain'])
print(dataframe)

       Rain on Tommorrow  Predition of Rain
0                      1                  0
1                      1                  0
2                      0                  0
3                      0                  1
4                      0                  0
...                  ...                ...
29087                  0                  1
29088                  0                  0
29089                  1                  0
29090                  0                  0
29091                  0                  0

[29092 rows x 2 columns]


In [158]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.8521930427608965